# Generated by Django 4.2.5 on 2023-09-10 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0005_watchlist_avg_rating_watchlist_number_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='avg_rating',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='number_rating',
        ),
    ]
